### ISSUE TITLE
Who is on call API

### ISSUE THREAD

**Issue by DanCarlyon** [DanCarlyon/opsgenie-sdk-revived#29]
We should implement the who is on call api

https://docs.opsgenie.com/docs/who-is-on-call-api

**Comment by joshrichards37** [comment]
@DanCarlyon think I've covered this issue in https://github.com/DanCarlyon/opsgenie-sdk-revived/pull/30 

Gets who's on call for a given schedule id.

**Comment by DanCarlyon** [comment]
[0.1.11](https://www.npmjs.com/package/opsgenie-sdk-revived/v/0.1.11) published including this feature
